Builtin echo
Saphirac/minishell pull request #18
Opened 2023-03-11 19:35 UTC by JonathanDUFOUR

The made changes are related to the issue https://github.com/Saphirac/minishell/issues/4.
The builtin `echo` has been implemented and tested.

2023-03-12 14:46 UTC, JonathanDUFOUR commented
The `env` builtin has also been implemented and tested.

2023-03-12 18:48 UTC, Saphirac commented on include/shell.h
> -# include "minishell.h"
Need to re-add minishell.h

2023-03-12 18:54 UTC, Saphirac requested changes
Warning : need to put back `minishell.h` instead of `list.h` inside shell.h

2023-03-13 17:46 UTC, JonathanDUFOUR commented
The `export` builtin has also been implemented and tested.

2023-03-13 17:59 UTC, Saphirac commented on include/minishell.h
> +int		surprise(void);
Approved.

2023-03-13 18:03 UTC, Saphirac approved these changes

2023-03-13 18:03 UTC, merged